feature/82: Add partner to send answer
LautaroDaRosa/Proyecto-Topicos-Avanzados pull request #44
Opened 2023-11-13 03:29 UTC by jeronimo-espiga

2023-11-14 21:23 UTC, SantiagoVillalba requested changes
En el answer service ahora tenes que usar User no provider, porque sino capaz que buscas y no encontras un partner que respondio, por tanto vas a tener que usar el IUserRepository, y luego el getAnswers() de abajo segun el ERole tenes que ir a buscar las answers list en el provider repository o en el partner repository

2023-11-14 21:23 UTC, SantiagoVillalba commented on backend/src/main/java/los/trainees/backend/entity/Partner.java
> +    private String logo;
Hay que sacar la variable esta de logo

2023-11-14 21:23 UTC, SantiagoVillalba commented on backend/src/main/java/los/trainees/backend/entity/Partner.java
>      private String rut;
porque le sacaste el unique?

2023-11-14 21:23 UTC, SantiagoVillalba commented on backend/src/main/java/los/trainees/backend/controller/AnswerController.java
>      public List<AnswerData> getAnswersFromProvider() {
Cambiale el nombre a getAnswers nomas

2023-11-14 21:24 UTC, SantiagoVillalba commented
Hace que te anden los test andes de subir algo!!!!

2023-11-25 00:57 UTC, SantiagoVillalba approved these changes

2023-11-25 01:16 UTC, CGonzaloMartinez approved these changes

2023-11-25 01:16 UTC, merged